⍝ Write an expression that produces a vector of 17 numbers, the first being 23,
⍝ with each subsequent number being equal to the preceding plus 11.

⍝ We can simply add multiples of 11. These can be generated by obtaining a
⍝ 17-element vector starting at 0, then containing those multiples:
⍝ 11×(⍳17)-1

⍝ In total,

23+11×(⍳17)-1

⍝ The book has this:

12+11×⍳17

⍝ ... which is of course simpler.

